name: CurlCraft
version: 1.0.0
description: The Minecraft plugin that adds RESTful API endpoints to your server, allowing for an unlimited amount of crazy.

author: irritatingness 
website: irritatingness.com

main: com.irritatingness.CurlCraft